apiVersion: apps/v1
kind: Deployment
metadata:
  name: trabalho-devops-main
spec:
    replicas: 3
    selector:
        matchLabels:
        app: trabalho-devops-main
    template:
        metadata:
        labels:
            app: trabalho-devops-main
        spec:
        containers:
          - name: trabalho-devops-main
            image: Ito2005/trabalho-devops-main
            ports:
            - containerPort: 8000