apiVersion: apps/v1
kind: Deployment
metadata:
  name: trabalho-devops
spec:
    replicas: 3
    selector:
        matchLabels:
        app: trabalho-devops-main
    template:
        metadata:
        labels:
            app: trabalho-devops-main
        spec:
        containers:
        - name: trabalho-devops
          image: Ito2005/trabalho-devops
          ports:
            - containerPort: 8000
