apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: trabalho-devops
    newName: Ito2005/trabalho-devops-main-k8s
    newTag: c58b625834eb8b45c0d3d3b45ba4cbc288fc5146